/*
 * File: app/view/wndLogin.js
 * Date: Sun Mar 22 2020 20:33:10 GMT+1000 (E. Australia Standard Time)
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JumboPets.view.wndLogin', {
    extend: 'Ext.window.Window',
    alias: 'widget.wndlogin',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.button.Button',
        'Ext.Img'
    ],

    modal: true,
    autoShow: true,
    height: 228,
    id: 'wndLogin',
    width: 326,
    layout: 'fit',
    closable: false,
    title: 'Login to Jumbo Pets',
    defaultListenerScope: true,

    listeners: {
        afterrender: 'onWndLoginAfterRender'
    },
    items: [
        {
            xtype: 'form',
            border: false,
            layout: 'absolute',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    x: 50,
                    y: 80,
                    id: 'txtLoginEmail',
                    fieldLabel: 'Username',
                    labelWidth: 60,
                    value: 'user',
                    vtype: 'alpha'
                },
                {
                    xtype: 'textfield',
                    x: 50,
                    y: 110,
                    id: 'txtLoginPassword',
                    fieldLabel: 'Password',
                    labelWidth: 60,
                    value: 'password',
                    inputType: 'password',
                    enableKeyEvents: true,
                    listeners: {
                        keyup: 'onTxtLoginPasswordKeyup'
                    }
                },
                {
                    xtype: 'checkboxfield',
                    x: 114,
                    y: 135,
                    id: 'chkRememberMe',
                    fieldLabel: '',
                    boxLabel: 'Remember Me'
                },
                {
                    xtype: 'button',
                    x: 210,
                    y: 160,
                    id: 'btnLogin',
                    icon: '/images/icons/png/16x16/Key.png',
                    text: 'Login',
                    listeners: {
                        click: 'onButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    x: 50,
                    y: 160,
                    icon: '/images/icons/png/16x16/LightBulb.png',
                    text: 'Forgot Password'
                },
                {
                    xtype: 'image',
                    x: 80,
                    y: 10,
                    height: 57,
                    width: 160,
                    src: '/images/logo.png'
                }
            ]
        }
    ],

    onWndLoginAfterRender: function(component, eOpts) {
        function accessCookie(cookieName)
        {
            var name = cookieName + "=";
            var allCookieArray = document.cookie.split(';');
            for(var i=0; i<allCookieArray.length; i++)
            {
                var temp = allCookieArray[i].trim();
                if (temp.indexOf(name)==0)
                    return temp.substring(name.length,temp.length);
            }
            return "";
        }
        var email = accessCookie("remember");
        if (email) {
            Ext.getCmp('txtLoginEmail').setValue(email);
            Ext.getCmp('chkRememberMe').setValue(true);
        }
    },

    onTxtLoginPasswordKeyup: function(textfield, e, eOpts) {
        if (e.keyCode == 13) {
            Ext.getCmp('btnLogin').fireEvent('click');
        }
    },

    onButtonClick: function(button, e, eOpts) {
        var username = Ext.getCmp('txtLoginEmail').getValue();
        var password = Ext.getCmp('txtLoginPassword').getValue();

        Ext.getCmp('wndLogin').close();
        var form = Ext.create('JumboPets.view.frmMain', {
            renderTo: Ext.getBody()
        });
        var win = window,
            doc = document,
            docElem = doc.documentElement,
            body = doc.getElementsByTagName('body')[0],
            x = win.innerWidth || docElem.clientWidth || body.clientWidth,
            y = win.innerHeight|| docElem.clientHeight|| body.clientHeight;
        Ext.getCmp('frmMain').setHeight(y);
        Ext.getCmp('frmMain').setWidth(x);

    }

});