/*
 * File: app/view/frmBody.js
 * Date: Fri Mar 20 2020 16:01:06 GMT+1000 (E. Australia Standard Time)
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JumboPets.view.frmBody', {
    extend: 'Ext.form.Panel',
    alias: 'widget.frmbody',

    requires: [
        'JumboPets.view.frmBodyViewModel',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.ComboBox',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'frmbody'
    },
    height: 498,
    width: 770,
    bodyPadding: 20,
    title: '',

    layout: {
        type: 'table',
        columns: 2
    },
    items: [
        {
            xtype: 'fieldset',
            height: 200,
            padding: 5,
            width: 300,
            title: 'Parameters',
            items: [
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'Description',
                    name: 'description',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'URL',
                    name: 'url',
                    value: ''
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    fieldLabel: 'Method',
                    name: 'method',
                    store: 'strMethods'
                }
            ]
        },
        {
            xtype: 'form',
            height: 200,
            margin: 5,
            width: 300,
            layout: 'form',
            bodyPadding: 10,
            title: 'Fields'
        },
        {
            xtype: 'container',
            width: 300,
            items: [
                {
                    xtype: 'label',
                    text: 'Request:'
                },
                {
                    xtype: 'textareafield',
                    minHeight: 400,
                    width: 300,
                    fieldLabel: ''
                }
            ]
        },
        {
            xtype: 'container',
            width: 300,
            items: [
                {
                    xtype: 'label',
                    text: 'Response:'
                },
                {
                    xtype: 'textareafield',
                    minHeight: 400,
                    width: 300,
                    fieldLabel: ''
                }
            ]
        }
    ],

    setUp: function(parameters) {
        this.getForm().setValues(parameters);
    },

    post: function() {

    }

});