/*
 * File: app/view/frmMain.js
 * Date: Fri Mar 20 2020 16:01:06 GMT+1000 (E. Australia Standard Time)
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JumboPets.view.frmMain', {
    extend: 'Ext.form.Panel',
    alias: 'widget.frmmain',

    requires: [
        'JumboPets.view.frmMainViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'frmmain'
    },
    height: 424,
    id: 'frmMain',
    width: 848,
    layout: 'fit',
    title: 'Jumbo Pets',

    items: [
        {
            xtype: 'tabpanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'Pet',
                    items: [
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Upload Image'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Add'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Update'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Find By Status'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Find By Tags'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Find By ID'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Update with Form'
                                },
                                {
                                    xtype: 'panel',
                                    width: 604,
                                    title: 'Delete'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Store',
                    items: [
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Order Pet'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Find Order'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Delete Order'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Inventory'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'User',
                    items: [
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Create w/ Array'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Cr4eate w/ List'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Get'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Update'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Delete'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Login'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Logout'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Create'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});